import turtle
tela = turtle.Screen()
tela.bgcolor("black")
tartaruga = turtle.Turtle()
tartaruga.shape("turtle")
tartaruga.color("blue2")
tartaruga.begin_fill()
for i in range(2):
	tartaruga.forward(50)
	tartaruga.left(90)
	tartaruga.forward(100)
	tartaruga.left(90)
tartaruga.end_fill()
tartaruga.pu()
tartaruga.forward(50)
tartaruga.pd()
tartaruga.color("white")
tartaruga.begin_fill()
for i in range(2):
	tartaruga.forward(50)
	tartaruga.left(90)
	tartaruga.forward(100)
	tartaruga.left(90)
tartaruga.end_fill()
tartaruga.pu()
tartaruga.forward(50)
tartaruga.pd()
tartaruga.color("red")
tartaruga.begin_fill()
for i in range(2):
	tartaruga.forward(50)
	tartaruga.left(90)
	tartaruga.forward(100)
	tartaruga.left(90)
tartaruga.end_fill()


turtle.mainloop()