import turtle
tela = turtle.Screen()
tela.bgcolor("black")
kaka = turtle.Turtle()
kaka.goto(-75,50)
kaka.color("green2")
kaka.begin_fill()
for i in range(2):
	kaka.fd(150)
	kaka.rt(90)
	kaka.fd(100)
	kaka.rt(90)
kaka.end_fill()
kaka.color("yellow")
kaka.pu()
kaka.goto(-60,0)
kaka.pd()
kaka.begin_fill()
kaka.goto(0,30)
kaka.goto(60,0)
kaka.goto(0,-30)
kaka.goto(-60,0)
kaka.end_fill()
kaka.color("blue")
kaka.pu()
kaka.goto(0,-20)
kaka.pd()
kaka.begin_fill()
kaka.circle(20)
kaka.end_fill()
kaka.ht()
turtle.mainloop()